# Generated by Django 4.2.9 on 2026-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("books_scraped", models.IntegerField(default=0)),
                ("status", models.CharField(default="running", max_length=50)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "author",
                    models.CharField(blank=True, default="Unknown", max_length=300),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("num_reviews", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("genre", models.CharField(blank=True, default="", max_length=200)),
                ("price", models.CharField(blank=True, default="", max_length=50)),
                (
                    "availability",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("book_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "cover_image",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("ai_genre", models.CharField(blank=True, default="", max_length=200)),
                (
                    "ai_sentiment",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("ai_sentiment_score", models.FloatField(blank=True, null=True)),
                ("ai_tags", models.JSONField(blank=True, default=list)),
                ("embeddings_stored", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(
                        fields=["ai_genre"], name="books_book_ai_genr_905a40_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="books_book_rating_d06a65_idx"
                    ),
                ],
            },
        ),
    ]
