"""
Management command: seed_books
Seeds the database with sample books so the app works without scraping.
Usage: python manage.py seed_books
"""
import random
from django.core.management.base import BaseCommand
from books.models import Book

SAMPLE_BOOKS = [
    {
        "title": "A Light in the Attic",
        "author": "Shel Silverstein",
        "rating": 3.0,
        "description": "A Light in the Attic is a book of poems that speaks directly to children's sense of play and imagination. Filled with absurd situations, outrageous characters, and a wry, gentle irreverence toward adult rules, it shows young readers that poetry can be funny.",
        "genre": "Poetry",
        "price": "£51.77",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html",
        "cover_image": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg",
        "ai_summary": "A beloved collection of whimsical poems that captures childhood imagination and playfulness with humor and heart.",
        "ai_genre": "Poetry",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.75,
        "ai_tags": ["poetry", "children", "humor", "imagination", "playful"],
        "embeddings_stored": False,
    },
    {
        "title": "Tipping the Velvet",
        "author": "Sarah Waters",
        "rating": 1.0,
        "description": "Nan King, an oyster girl, is captivated by the music hall phenomenon Kitty Butler, a male impersonator extraordinaire treading the boards in Canterbury. Watching Kitty nightly, Nan becomes entranced by her beauty and comic genius.",
        "genre": "Historical Fiction",
        "price": "£53.74",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html",
        "cover_image": "https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg",
        "ai_summary": "A vivid Victorian coming-of-age story following a young woman's passionate journey through love, loss, and self-discovery in London's music halls.",
        "ai_genre": "Historical Fiction",
        "ai_sentiment": "Neutral",
        "ai_sentiment_score": 0.1,
        "ai_tags": ["historical", "romance", "Victorian", "identity", "music-hall"],
        "embeddings_stored": False,
    },
    {
        "title": "Soumission",
        "author": "Michel Houellebecq",
        "rating": 1.0,
        "description": "In the very near future, a radical Muslim party has swept to power in France. The cynical narrator, a literary professor, tries to find meaning in a world upended by political and religious upheaval.",
        "genre": "Literary Fiction",
        "price": "£50.10",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/catalogue/soumission_998/index.html",
        "cover_image": "https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662d2f814.jpg",
        "ai_summary": "A provocative political novel exploring religion, identity and disillusionment in a near-future France under Islamic governance.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.3,
        "ai_tags": ["political", "dystopia", "religion", "France", "satire"],
        "embeddings_stored": False,
    },
    {
        "title": "Sharp Objects",
        "author": "Gillian Flynn",
        "rating": 4.0,
        "description": "Fresh from a brief stay at a psych hospital, reporter Camille Preaker faces a troubling assignment: she must travel to her tiny hometown to cover the murders of two preteen girls.",
        "genre": "Mystery",
        "price": "£47.82",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/catalogue/sharp-objects_997/index.html",
        "cover_image": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg",
        "ai_summary": "A gripping psychological thriller about a journalist investigating child murders in her hometown while confronting her own haunting past.",
        "ai_genre": "Mystery",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.65,
        "ai_tags": ["thriller", "mystery", "psychological", "dark", "suspense"],
        "embeddings_stored": False,
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "rating": 5.0,
        "description": "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us.",
        "genre": "History",
        "price": "£54.23",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A sweeping intellectual journey through the entire span of human history, exploring how Homo sapiens came to dominate and transform the planet.",
        "ai_genre": "History",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.6,
        "ai_tags": ["history", "humanity", "evolution", "culture", "science"],
        "embeddings_stored": False,
    },
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "rating": 4.0,
        "description": "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
        "genre": "Literary Fiction",
        "price": "£29.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A magical and life-affirming story about regret, hope and second chances, set in a library between life and death.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.8,
        "ai_tags": ["magical-realism", "philosophy", "self-discovery", "hope", "library"],
        "embeddings_stored": False,
    },
    {
        "title": "Dune",
        "author": "Frank Herbert",
        "rating": 5.0,
        "description": "Set in the distant future amidst a feudal interstellar society, Dune tells the story of young Paul Atreides whose family accepts control of the desert planet Arrakis.",
        "genre": "Science Fiction",
        "price": "£42.50",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "An epic science fiction saga set on a desert planet that masterfully blends politics, religion, ecology, and human destiny.",
        "ai_genre": "Science Fiction",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.7,
        "ai_tags": ["sci-fi", "epic", "desert", "prophecy", "politics"],
        "embeddings_stored": False,
    },
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "rating": 5.0,
        "description": "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear reveals practical strategies that will teach you exactly how to form good habits.",
        "genre": "Self-Help",
        "price": "£16.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A practical guide to building better habits and breaking bad ones through small, incremental changes that compound into remarkable results.",
        "ai_genre": "Self-Help",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.9,
        "ai_tags": ["habits", "productivity", "self-improvement", "psychology", "success"],
        "embeddings_stored": False,
    },
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "rating": 4.0,
        "description": "A portrait of the Jazz Age in all of its decadence and excess. Nick Carraway arrives in New York to learn the bond business, rents a house next to Jay Gatsby's mansion.",
        "genre": "Literary Fiction",
        "price": "£9.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A timeless critique of the American Dream set in the Roaring Twenties, exploring wealth, obsession, and the hollowness of high society.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Neutral",
        "ai_sentiment_score": -0.1,
        "ai_tags": ["classic", "American Dream", "Jazz Age", "wealth", "obsession"],
        "embeddings_stored": False,
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "rating": 5.0,
        "description": "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic attains the qualities of memory.",
        "genre": "Science Fiction",
        "price": "£8.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A chilling dystopian masterpiece about totalitarian control, surveillance, and the destruction of individual truth in a perpetual war state.",
        "ai_genre": "Science Fiction",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.8,
        "ai_tags": ["dystopia", "totalitarianism", "surveillance", "classic", "political"],
        "embeddings_stored": False,
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "rating": 5.0,
        "description": "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extraordinary as any ever found.",
        "genre": "Literary Fiction",
        "price": "£11.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A spiritual adventure about following your dreams and discovering your Personal Legend through a shepherd boy's journey across the desert.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.85,
        "ai_tags": ["philosophy", "journey", "destiny", "spiritual", "inspirational"],
        "embeddings_stored": False,
    },
    {
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "rating": 4.0,
        "description": "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne's fifth wedding anniversary. When Amy's the apparent victim in a bizarre murder case, the media frenzy descends.",
        "genre": "Mystery",
        "price": "£14.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A twisting psychological thriller told from two unreliable perspectives about a marriage gone terribly wrong and the truth buried beneath.",
        "ai_genre": "Mystery",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.5,
        "ai_tags": ["thriller", "psychological", "marriage", "suspense", "twist"],
        "embeddings_stored": False,
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "rating": 5.0,
        "description": "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. Scout Finch watches her father Atticus Finch defend a black man accused of a terrible crime.",
        "genre": "Literary Fiction",
        "price": "£8.49",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A powerful exploration of racial injustice and moral growth through the eyes of a young girl in the American South.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.6,
        "ai_tags": ["justice", "racism", "childhood", "moral-growth", "classic"],
        "embeddings_stored": False,
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "rating": 5.0,
        "description": "Bilbo Baggins is a hobbit who enjoys a comfortable life until the wizard Gandalf and thirteen dwarves arrive to recruit him for a treasure hunt against the dragon Smaug.",
        "genre": "Fantasy",
        "price": "£10.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A charming adventure following a reluctant hobbit on an epic quest through Middle-earth filled with magic, danger, and dragon treasure.",
        "ai_genre": "Fantasy",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.82,
        "ai_tags": ["adventure", "fantasy", "dragons", "quest", "friendship"],
        "embeddings_stored": False,
    },
    {
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "rating": 4.0,
        "description": "A dystopian novel set in a futuristic World State where citizens are genetically modified and socially conditioned to serve a ruling order. Bernard Marx begins to question the happiness imposed upon him.",
        "genre": "Science Fiction",
        "price": "£9.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A visionary dystopia exploring a world of engineered happiness where individuality and free thought are the ultimate rebellion.",
        "ai_genre": "Science Fiction",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.45,
        "ai_tags": ["dystopia", "genetic-engineering", "society", "freedom", "classic"],
        "embeddings_stored": False,
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "rating": 5.0,
        "description": "A witty romantic novel following Elizabeth Bennet as she navigates issues of manners, upbringing, morality, and marriage in Georgian England, particularly her evolving relationship with the proud Mr. Darcy.",
        "genre": "Romance",
        "price": "£6.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A sparkling romantic comedy of manners that skewers class prejudice while celebrating wit, independence, and love.",
        "ai_genre": "Romance",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.78,
        "ai_tags": ["romance", "classic", "society", "marriage", "wit"],
        "embeddings_stored": False,
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "rating": 4.0,
        "description": "Holden Caulfield recounts his experiences wandering around New York City after being expelled from prep school, offering a raw critique of adult phoniness and teenage alienation.",
        "genre": "Literary Fiction",
        "price": "£7.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "An iconic coming-of-age novel capturing the angst and rebellion of adolescence through an unforgettable narrative voice.",
        "ai_genre": "Literary Fiction",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.35,
        "ai_tags": ["coming-of-age", "alienation", "rebellion", "classic", "youth"],
        "embeddings_stored": False,
    },
    {
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "rating": 5.0,
        "description": "Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind explaining the two systems that drive the way we think: fast intuitive thinking and slow deliberate thinking.",
        "genre": "Psychology",
        "price": "£14.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A transformative exploration of cognitive biases and dual-process theory that reshapes how we understand human decision-making.",
        "ai_genre": "Psychology",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.55,
        "ai_tags": ["psychology", "cognition", "bias", "decision-making", "science"],
        "embeddings_stored": False,
    },
    {
        "title": "The Girl with the Dragon Tattoo",
        "author": "Stieg Larsson",
        "rating": 4.0,
        "description": "Journalist Mikael Blomkvist and the brilliant but troubled hacker Lisbeth Salander team up to investigate the disappearance of a young woman from a wealthy family decades ago.",
        "genre": "Thriller",
        "price": "£12.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A gripping Nordic thriller weaving together corporate corruption, family secrets, and a brilliant outcast hacker.",
        "ai_genre": "Thriller",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.55,
        "ai_tags": ["thriller", "mystery", "hacker", "Nordic-noir", "corruption"],
        "embeddings_stored": False,
    },
    {
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "rating": 4.0,
        "description": "Explores the science behind habit creation and reformation. Duhigg explains why habits exist and how they can be changed, with stories from boardrooms to civil rights movements.",
        "genre": "Self-Help",
        "price": "£13.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A fascinating dive into the neuroscience of habits and practical strategies for transforming personal and organizational behavior.",
        "ai_genre": "Self-Help",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.72,
        "ai_tags": ["habits", "neuroscience", "behavior", "productivity", "change"],
        "embeddings_stored": False,
    },
    {
        "title": "A Game of Thrones",
        "author": "George R.R. Martin",
        "rating": 5.0,
        "description": "In a land where summers span decades and winters can last a lifetime, the noble houses of Westeros vie for control of the Iron Throne in a ruthless game of politics, war, and betrayal.",
        "genre": "Fantasy",
        "price": "£15.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "An epic dark fantasy of political intrigue, war, and betrayal set in a richly imagined medieval world.",
        "ai_genre": "Fantasy",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.3,
        "ai_tags": ["fantasy", "politics", "war", "epic", "betrayal"],
        "embeddings_stored": False,
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "rating": 5.0,
        "description": "A memoir about a young girl who grows up in a survivalist family in Idaho and never sets foot in a classroom. She eventually earns a PhD from Cambridge University through sheer determination.",
        "genre": "Biography",
        "price": "£11.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A riveting memoir of resilience and transformation from an isolated survivalist upbringing to the halls of Cambridge.",
        "ai_genre": "Biography",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.65,
        "ai_tags": ["memoir", "education", "resilience", "family", "transformation"],
        "embeddings_stored": False,
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "rating": 5.0,
        "description": "Ryland Grace wakes up alone on a spaceship with no memory. As he pieces together his mission, he realizes he is the last hope for saving Earth from an extinction-level threat.",
        "genre": "Science Fiction",
        "price": "£13.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A thrilling sci-fi adventure about an amnesiac astronaut racing to save humanity with ingenious science and an unexpected alien friend.",
        "ai_genre": "Science Fiction",
        "ai_sentiment": "Positive",
        "ai_sentiment_score": 0.88,
        "ai_tags": ["space", "science", "survival", "friendship", "adventure"],
        "embeddings_stored": False,
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "rating": 4.0,
        "description": "Alicia Berenson shoots her husband five times in the face and then never speaks another word. A criminal psychotherapist becomes obsessed with uncovering her truth.",
        "genre": "Thriller",
        "price": "£10.99",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A shocking psychological thriller about silence, obsession, and a devastating twist that reframes everything.",
        "ai_genre": "Thriller",
        "ai_sentiment": "Negative",
        "ai_sentiment_score": -0.6,
        "ai_tags": ["psychological", "thriller", "twist", "silence", "obsession"],
        "embeddings_stored": False,
    },
    {
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "rating": 5.0,
        "description": "Kya Clark, the 'Marsh Girl,' grows up alone in the marshes of North Carolina. When the popular local quarterback is found dead, she becomes the prime suspect.",
        "genre": "Mystery",
        "price": "£11.49",
        "availability": "In stock",
        "book_url": "https://books.toscrape.com/",
        "cover_image": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg",
        "ai_summary": "A lyrical mystery interweaving nature, loneliness, and murder in the hauntingly beautiful North Carolina marshlands.",
        "ai_genre": "Mystery",
        "ai_sentiment": "Neutral",
        "ai_sentiment_score": 0.15,
        "ai_tags": ["nature", "mystery", "isolation", "coming-of-age", "love"],
        "embeddings_stored": False,
    },
]


class Command(BaseCommand):
    help = "Seed the database with sample books for demo purposes"

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true", help="Clear existing books first")

    def handle(self, *args, **options):
        if options["clear"]:
            Book.objects.all().delete()
            self.stdout.write(self.style.WARNING("Cleared all existing books."))

        created = 0
        for data in SAMPLE_BOOKS:
            book, is_new = Book.objects.get_or_create(title=data["title"], defaults=data)
            if is_new:
                created += 1
                self.stdout.write(f"  + Added: {book.title}")
            else:
                self.stdout.write(f"  . Exists: {book.title}")

        self.stdout.write(self.style.SUCCESS(f"\nDone! {created} new books added. {Book.objects.count()} total."))
